// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfmefxbidfeppyquyzww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbWVmeGJpZGZlcHB5cXV5end3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDIyNzksImV4cCI6MjA1OTU3ODI3OX0.4UYY9y3_hQr4cix-_hPo-GqTgCXilMV6GFHfNAsFpVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);